
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author T_Khosyi
 */
public class KonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        RBCelcius2 = new javax.swing.JRadioButton();
        RBFahrenheit2 = new javax.swing.JRadioButton();
        RBReamur2 = new javax.swing.JRadioButton();
        RBKelvin2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        BTNKonversi = new javax.swing.JButton();
        BTNReset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        RBCelcius1 = new javax.swing.JRadioButton();
        RBFahrenheit1 = new javax.swing.JRadioButton();
        RBReamur1 = new javax.swing.JRadioButton();
        RBKelvin1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JPIsi = new javax.swing.JPanel();
        isi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROGRAM KONVERSI SUHU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(0, 101, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));

        buttonGroup2.add(RBCelcius2);
        RBCelcius2.setText("CELCIUS");
        RBCelcius2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCelcius2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBFahrenheit2);
        RBFahrenheit2.setText("FAHRENHEIT");
        RBFahrenheit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFahrenheit2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBReamur2);
        RBReamur2.setText("REAMUR");
        RBReamur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBReamur2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBKelvin2);
        RBKelvin2.setText("KELVIN");
        RBKelvin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBKelvin2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("--- Pilih Suhu Akhir ---");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBKelvin2)
                            .addComponent(RBReamur2)
                            .addComponent(RBFahrenheit2)
                            .addComponent(RBCelcius2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(RBCelcius2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBFahrenheit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBReamur2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBKelvin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNKonversi.setText("KONVERSI");
        BTNKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKonversiActionPerformed(evt);
            }
        });

        BTNReset.setText("RESET");
        BTNReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 101, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));

        buttonGroup1.add(RBCelcius1);
        RBCelcius1.setText("CELCIUS");
        RBCelcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCelcius1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBFahrenheit1);
        RBFahrenheit1.setText("FAHRENHEIT");

        buttonGroup1.add(RBReamur1);
        RBReamur1.setText("REAMUR");

        buttonGroup1.add(RBKelvin1);
        RBKelvin1.setText("KELVIN");
        RBKelvin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBKelvin1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("--- Pilih Suhu Awal ---");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBKelvin1)
                    .addComponent(RBReamur1)
                    .addComponent(RBFahrenheit1)
                    .addComponent(RBCelcius1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(RBCelcius1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBFahrenheit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBReamur1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBKelvin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Masukkan Nominal Suhu Awal");

        TFInput.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Suhu Akhir");

        JPIsi.setBackground(new java.awt.Color(0, 101, 153));
        JPIsi.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 0, 0)));

        isi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isi.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPIsiLayout = new javax.swing.GroupLayout(JPIsi);
        JPIsi.setLayout(JPIsiLayout);
        JPIsiLayout.setHorizontalGroup(
            JPIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPIsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPIsiLayout.setVerticalGroup(
            JPIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPIsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFInput)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTNKonversi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNKonversi)
                            .addComponent(BTNReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPIsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBKelvin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBKelvin2ActionPerformed
        // TODO add your handling code here:
        if (RBKelvin2.isSelected()==true){
            TFInput.setEditable(true);
            }
                else {
            TFInput.setEditable(false);
            TFInput.setText("");
            }
    }//GEN-LAST:event_RBKelvin2ActionPerformed

    private void RBCelcius2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCelcius2ActionPerformed
        if (RBCelcius2.isSelected()==true){
            TFInput.setEditable(true);
            }
                else {
            TFInput.setEditable(false);
            TFInput.setText("");
            }
    }//GEN-LAST:event_RBCelcius2ActionPerformed

    private void BTNResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetActionPerformed
        // TODO add your handling code here:
        TFInput.setText(null);
        isi.setText(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_BTNResetActionPerformed

    private void RBCelcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCelcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBCelcius1ActionPerformed

    private void RBKelvin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBKelvin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBKelvin1ActionPerformed

    private void BTNKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKonversiActionPerformed
        // TODO add your handling code here:
        //Celcius
        if (RBCelcius1.isSelected()==true && RBFahrenheit2.isSelected()==true){
            float cel = Float.parseFloat(TFInput.getText());
            double fah = (1.8*cel)+32;
            isi.setText(String.valueOf(fah));
        }
        
        else if (RBCelcius1.isSelected()==true && RBReamur2.isSelected()==true){
            float cel = Float.parseFloat(TFInput.getText());
            double rea = (0.8*cel);
            isi.setText(String.valueOf(rea));
        }
        
        else if (RBCelcius1.isSelected()==true && RBKelvin2.isSelected()==true){
            float cel = Float.parseFloat(TFInput.getText());
            double kel = (cel+273);
            isi.setText(String.valueOf(kel));
            
        //Fahrenfeit
        }
        else if (RBFahrenheit1.isSelected()==true && RBCelcius2.isSelected()==true){
            float fah = Float.parseFloat(TFInput.getText());
            double cel = (fah-32)/1.8;
            isi.setText(String.valueOf(cel));
        }
        
        else if (RBFahrenheit1.isSelected()==true && RBReamur2.isSelected()==true){
            float fah = Float.parseFloat(TFInput.getText());
            double rea = (fah-32)/2.25;
            isi.setText(String.valueOf(rea));
        }
        
        else if (RBFahrenheit1.isSelected()==true && RBKelvin2.isSelected()==true){
            float fah = Float.parseFloat(TFInput.getText());
            double kel = (fah+459)/1.8;
            isi.setText(String.valueOf(kel));
        }
        
        //Reamur
        else if (RBReamur1.isSelected()==true && RBCelcius2.isSelected()==true){
            float rea = Float.parseFloat(TFInput.getText());
            double cel = (rea/0.8);
            isi.setText(String.valueOf(cel));
        }
        
        else if (RBReamur1.isSelected()==true && RBFahrenheit2.isSelected()==true){
            float rea = Float.parseFloat(TFInput.getText());
            double fah = (rea*2.25)+491.67;
            isi.setText(String.valueOf(fah)); 
        }
        
        else if (RBReamur1.isSelected()==true && RBKelvin2.isSelected()==true){
            float rea = Float.parseFloat(TFInput.getText());
            double kel = (rea/0.8)+273.15;
            isi.setText(String.valueOf(kel));
        }
        
        //Kelvin
        else if (RBKelvin1.isSelected()==true && RBCelcius2.isSelected()==true){
            float kel = Float.parseFloat(TFInput.getText());
            double cel = (kel-273.15);
            isi.setText(String.valueOf(cel));
        }
        
        else if (RBKelvin1.isSelected()==true && RBFahrenheit2.isSelected()==true){
            float kel = Float.parseFloat(TFInput.getText());
            double fah = (kel-273.15)*0.8;
            isi.setText(String.valueOf(fah));
        }
        
        else if (RBKelvin1.isSelected()==true && RBReamur2.isSelected()==true){
            float kel = Float.parseFloat(TFInput.getText());
            double rea = (kel*1.8)-459.67;
            isi.setText(String.valueOf(rea));
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Maaf, Pilihan Suhu tidak boleh sama","Error",JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_BTNKonversiActionPerformed

    private void RBFahrenheit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFahrenheit2ActionPerformed
        // TODO add your handling code here:
        if (RBFahrenheit2.isSelected()==true){
            TFInput.setEditable(true);
            }
                else {
            TFInput.setEditable(false);
            TFInput.setText("");
            }
    }//GEN-LAST:event_RBFahrenheit2ActionPerformed

    private void RBReamur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBReamur2ActionPerformed
        // TODO add your handling code here:
        if (RBReamur2.isSelected()==true){
            TFInput.setEditable(true);
            }
                else {
            TFInput.setEditable(false);
            TFInput.setText("");
            }
    }//GEN-LAST:event_RBReamur2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNKonversi;
    private javax.swing.JButton BTNReset;
    private javax.swing.JPanel JPIsi;
    private javax.swing.JRadioButton RBCelcius1;
    private javax.swing.JRadioButton RBCelcius2;
    private javax.swing.JRadioButton RBFahrenheit1;
    private javax.swing.JRadioButton RBFahrenheit2;
    private javax.swing.JRadioButton RBKelvin1;
    private javax.swing.JRadioButton RBKelvin2;
    private javax.swing.JRadioButton RBReamur1;
    private javax.swing.JRadioButton RBReamur2;
    private javax.swing.JTextField TFInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel isi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
