/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Postest6;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * @author Khosyi
 */
public class FormRumahSakit extends javax.swing.JFrame {

    /**
     * Creates new form FormRumahSakit
     */
    public FormRumahSakit() {
        initComponents();
    }
    
    private DefaultTableModel model;
    private Connection con = konek.getConnection();
    private Statement stt;
    private ResultSet rss;

    private void InitTable(){
        model = new DefaultTableModel();
        model.addColumn("NAMA PASIEN");
        model.addColumn("TTL");
        model.addColumn("USIA");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("DIAGNOSA");
        model.addColumn("DOKTER");
        model.addColumn("RUANGAN");
        model.addColumn("TGL_MASUK");
        jTable1.setModel(model);
    }
    
    private void TampilData(){
        try{
    String sql = "Select * FROM rumahsakit";
    stt = con.createStatement();
    rss = stt.executeQuery(sql);
    while(rss.next()){
        Object[] o = new Object[9];
        o[0] = rss.getString("nama_pasien");
        o[1] = rss.getString("tl");
        o[2] = rss.getString("usia");
        o[3] = rss.getString("jk");
        o[4] = rss.getString("diagnosa");
        o[5] = rss.getString("dokter");
        o[6] = rss.getString("ruangan");
        o[7] = rss.getString("tgl_masuk");
        model.addRow(o);
        }
    }catch(SQLException e){
        System.out.println(e.getMessage());
    }
    }
    private void TambahData(String nama_pasien, String tl, int usia, String jk, String diagnosa, String dokter, String ruangan, String tgl_masuk){
        try{
            String sql =
                    "INSERT INTO rumahsakit VALUES (NULL ,'"+nama_pasien+"','"+tl+"','"+usia+"','"+
                    jk+"','"+diagnosa+"','"+dokter+"','"+ruangan+"','"+tgl_masuk+"')";
            stt = con.createStatement();
            stt.executeUpdate(sql);
            model.addRow(new Object []{nama_pasien,tl,usia,jk,diagnosa,dokter,ruangan,tgl_masuk});
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BTambahPasien = new javax.swing.JButton();
        BDataPasien = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tambahPasien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFTglLahir = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TFUsia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        CBDokter = new javax.swing.JComboBox<>();
        CBRuangan = new javax.swing.JComboBox<>();
        TFTglMasuk = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListDiagnosa = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BUlang = new javax.swing.JButton();
        dataPasien = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        TFCari = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CBCari = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Postest6/k.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORM PASIEN KHOSYI HOSPITAL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jalan Abdul Wahab Syahrani No. 3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        BTambahPasien.setText("Tambah Pasien");
        BTambahPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTambahPasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTambahPasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTambahPasienMouseExited(evt);
            }
        });
        jPanel3.add(BTambahPasien);

        BDataPasien.setText("Data Pasien");
        BDataPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BDataPasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BDataPasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BDataPasienMouseExited(evt);
            }
        });
        jPanel3.add(BDataPasien);

        BKeluar.setText("Keluar");
        BKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BKeluarMouseExited(evt);
            }
        });
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        jPanel4.setLayout(new java.awt.CardLayout());

        tambahPasien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Pasien");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TAMBAH PASIEAN");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Lahir");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Usia");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jenis Kelamin");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Dokter");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ruangan");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tanggal Masuk");

        TFNama.setEnabled(false);
        TFNama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNamaCaretUpdate(evt);
            }
        });

        TFTglLahir.setEnabled(false);
        TFTglLahir.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTglLahirCaretUpdate(evt);
            }
        });
        TFTglLahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTglLahirKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel14.setText("(*format yyyy-mm-dd)");

        TFUsia.setEnabled(false);
        TFUsia.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFUsiaCaretUpdate(evt);
            }
        });
        TFUsia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFUsiaKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tahun");

        buttonGroup1.add(lk);
        lk.setText("L");
        lk.setEnabled(false);

        buttonGroup1.add(pr);
        pr.setText("P");
        pr.setEnabled(false);

        CBDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Taufikurrahman Khosyi", "Dr. Muhammad Sarman Noorlah", "Dr. Muhammad Rijal", "Dr. Arif Fahrizal", "Dr. Kimebmen Simbolon", "Dr. Kahar Kasim Nusi" }));
        CBDokter.setEnabled(false);

        CBRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UGD", "ICU", "ICCU", "PICU", "HCU", "Ruang Operasi", "Ruang Bersalin", "Ruang Radiologi", "Ruang Rawat Inap" }));
        CBRuangan.setEnabled(false);

        TFTglMasuk.setEnabled(false);
        TFTglMasuk.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTglMasukCaretUpdate(evt);
            }
        });
        TFTglMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTglMasukKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel16.setText("(*format yyyy-mm-dd)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Diagnosa");

        ListDiagnosa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Kangker", "Diabetes", "Malaria", "Melahirkan", "Leukimia", "Asma", "Batuk", "Flu", "Sakit Gigi", "Gagal Ginjal", "Diare", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDiagnosa.setEnabled(false);
        jScrollPane1.setViewportView(ListDiagnosa);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        BTambah.setText("TAMBAH");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        jPanel11.add(BTambah);

        BSimpan.setText("SIMPAN");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        jPanel11.add(BSimpan);

        BUlang.setText("ULANG");
        BUlang.setEnabled(false);
        BUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUlangActionPerformed(evt);
            }
        });
        jPanel11.add(BUlang);

        javax.swing.GroupLayout tambahPasienLayout = new javax.swing.GroupLayout(tambahPasien);
        tambahPasien.setLayout(tambahPasienLayout);
        tambahPasienLayout.setHorizontalGroup(
            tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tambahPasienLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPasienLayout.createSequentialGroup()
                        .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(48, 48, 48)
                        .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPasienLayout.createSequentialGroup()
                                .addComponent(lk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pr))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPasienLayout.createSequentialGroup()
                                .addComponent(TFUsia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPasienLayout.createSequentialGroup()
                                .addComponent(TFTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addComponent(CBDokter, javax.swing.GroupLayout.Alignment.LEADING, 0, 351, Short.MAX_VALUE)
                            .addComponent(TFNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBRuangan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPasienLayout.createSequentialGroup()
                                .addComponent(TFTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(44, 44, 44)
                        .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(781, 781, 781))
        );
        tambahPasienLayout.setVerticalGroup(
            tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPasienLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(tambahPasienLayout.createSequentialGroup()
                        .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahPasienLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(CBDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(CBRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(TFTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(tambahPasienLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(TFTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TFUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(tambahPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lk)
                                    .addComponent(pr))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel4.add(tambahPasien, "card2");

        dataPasien.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("DATA PASIEN");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        TFCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFCariKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("BY");

        CBCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nama_pasien", "dokter" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFCari, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBCari, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFCari, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addComponent(CBCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dataPasienLayout = new javax.swing.GroupLayout(dataPasien);
        dataPasien.setLayout(dataPasienLayout);
        dataPasienLayout.setHorizontalGroup(
            dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(dataPasienLayout.createSequentialGroup()
                        .addGroup(dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataPasienLayout.setVerticalGroup(
            dataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jPanel4.add(dataPasien, "card3");

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyright 2017 Taufikurrahman Khosyi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(317, 317, 317))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));

        jLabel1.setText("SELAMAT DATANG DI APLIKASI FORM RUMAH SAKIT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(278, 278, 278))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTambahPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTambahPasienMouseClicked
        // TODO add your handling code here:
        tambahPasien.setVisible(true);
        dataPasien.setVisible(false);
    }//GEN-LAST:event_BTambahPasienMouseClicked

    private void BTambahPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTambahPasienMouseEntered
        // TODO add your handling code here:
        BTambahPasien.setBackground(Color.ORANGE);
    }//GEN-LAST:event_BTambahPasienMouseEntered

    private void BTambahPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTambahPasienMouseExited
        // TODO add your handling code here:
        BTambahPasien.setBackground(getBackground());
    }//GEN-LAST:event_BTambahPasienMouseExited

    private void BDataPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataPasienMouseClicked
        // TODO add your handling code here:
        tambahPasien.setVisible(false);
        dataPasien.setVisible(true);
    }//GEN-LAST:event_BDataPasienMouseClicked

    private void BDataPasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataPasienMouseEntered
        // TODO add your handling code here:
        BDataPasien.setBackground(Color.ORANGE);
    }//GEN-LAST:event_BDataPasienMouseEntered

    private void BDataPasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDataPasienMouseExited
        // TODO add your handling code here:
        BDataPasien.setBackground(getBackground());
    }//GEN-LAST:event_BDataPasienMouseExited

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BKeluarActionPerformed

    private void BKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BKeluarMouseClicked

    private void BKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseEntered
        // TODO add your handling code here:
        BKeluar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_BKeluarMouseEntered

    private void BKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseExited
        // TODO add your handling code here:
        BKeluar.setBackground(getBackground());
        
    }//GEN-LAST:event_BKeluarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        InitTable();
        TampilData();
    }//GEN-LAST:event_formWindowOpened

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        BUlang.setEnabled(true);
        BSimpan.setEnabled(true);
        BKeluar.setEnabled(true);
        TFNama.setEnabled(true);
        TFUsia.setEnabled(true);
        TFTglLahir.setEnabled(true);
        CBDokter.setEnabled(true);
        lk.setEnabled(true);
        pr.setEnabled(true);
        ListDiagnosa.setEnabled(true);
        CBRuangan.setEnabled(true);
        TFTglMasuk.setEnabled(true);
    }//GEN-LAST:event_BTambahActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        int simpan=JOptionPane.showConfirmDialog(this, "Simpan Data ?","Confirm Simpan",
        JOptionPane.YES_OPTION);
        if(simpan==JOptionPane.YES_OPTION){
        String nama_pasien = TFNama.getText();
        String tl = TFTglLahir.getText();
     //   String usia = TFUsia.getText();
        int usia = Integer.parseInt(TFUsia.getText());
        String jk=null;
        if(lk.isSelected()){
            jk = lk.getText();
        }
        else if(pr.isSelected()){
            jk =pr.getText();
        }
        else{
            JOptionPane.showMessageDialog(null,"Pilih Jenis Kelamin",
                    "Warning",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String dokter = CBDokter.getSelectedItem().toString();
        String ruangan = CBRuangan.getSelectedItem().toString();
        String tgl_masuk= TFTglMasuk.getText();
        String diagnosa = ListDiagnosa.getSelectedValuesList().toString();
        
        
        TambahData(nama_pasien, tl, usia, jk, diagnosa, dokter, ruangan, tgl_masuk);
    }
                                           

    
    }//GEN-LAST:event_BSimpanActionPerformed

    private void TFNamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNamaCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length()== 0 || TFTglLahir.getText().length()==0||
            TFUsia.getText().length()== 0 || TFTglMasuk.getText().length()==0)
                {
                    BSimpan.setEnabled(false);
        }
        else{
            BSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFNamaCaretUpdate

    private void TFTglLahirCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTglLahirCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length()== 0 || TFTglLahir.getText().length()==0||
            TFUsia.getText().length()== 0 || TFTglMasuk.getText().length()==0)
                {
                    BSimpan.setEnabled(false);
        }
        else{
            BSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFTglLahirCaretUpdate

    private void TFUsiaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFUsiaCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length()== 0 || TFTglLahir.getText().length()==0||
            TFUsia.getText().length()== 0 || TFTglMasuk.getText().length()==0)
                {
                    BSimpan.setEnabled(false);
        }
        else{
            BSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFUsiaCaretUpdate

    private void TFTglMasukCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTglMasukCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length()== 0 || TFTglLahir.getText().length()==0||
            TFUsia.getText().length()== 0 || TFTglMasuk.getText().length()==0)
                {
                    BSimpan.setEnabled(false);
        }
        else{
            BSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFTglMasukCaretUpdate

    private void TFUsiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsiaKeyPressed
        // TODO add your handling code here:
        TFUsia.addKeyListener(new KeyAdapter(){
             public void keyTyped(KeyEvent e){
                 char karakter = e.getKeyChar();
                 if(!((karakter >='0') && (karakter<='9') || (karakter == '\b'))){
                     e.consume();
                 }
             }
        });
    }//GEN-LAST:event_TFUsiaKeyPressed

    private void TFTglLahirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTglLahirKeyPressed
        // TODO add your handling code here:
        TFTglLahir.addKeyListener(new KeyAdapter(){
             public void keyTyped(KeyEvent e){
                 char karakter = e.getKeyChar();
                 if(!((karakter >='0') && (karakter<='9') || (karakter == '\b')) && (karakter != '-')){
                     e.consume();
                 }
             }
        });
    }//GEN-LAST:event_TFTglLahirKeyPressed

    private void TFTglMasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTglMasukKeyPressed
        // TODO add your handling code here:
        TFTglMasuk.addKeyListener(new KeyAdapter(){
             public void keyTyped(KeyEvent e){
                 char karakter = e.getKeyChar();
                 if(!((karakter >='0') && (karakter<='9') || (karakter == '\b')) && (karakter != '-')){
                     e.consume();
                 }
             }
        });
    }//GEN-LAST:event_TFTglMasukKeyPressed

    private void TFCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCariKeyTyped
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String caridengan = CBCari.getSelectedItem().toString();
        try {
            
           String sql="select * from rumahsakit where "+caridengan+" like '%"+TFCari.getText()+"%'";
           stt = con. createStatement();
            rss = stt. executeQuery(sql);
                       ResultSet rss=stt.executeQuery(sql);
            while (rss.next()) {
                Object[] o=new Object[9];
                o[0] = rss.getString("nama_pasien");
                o[1] = rss.getString("tl");
                o[2] = rss.getString("usia");
                o[3] = rss.getString("jk");
                o[4] = rss.getString("diagnosa");
                o[5] = rss.getString("dokter");
                o[6] = rss.getString("ruangan");
                o[7] = rss.getString("tgl_masuk");     
            model.addRow(o);
            }
            stt.close();
            rss.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }//GEN-LAST:event_TFCariKeyTyped

    private void BUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUlangActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFUsia.setText("");
        TFTglLahir.setText("");
        CBDokter.setSelectedItem("Dr. Taufikurrahman Khosyi");
        buttonGroup1.clearSelection();
        ListDiagnosa.getSelectedValuesList().toString().isEmpty();
        CBRuangan.setSelectedItem("UGD");
        TFTglMasuk.setText("");
    }//GEN-LAST:event_BUlangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRumahSakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDataPasien;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton BTambahPasien;
    private javax.swing.JButton BUlang;
    private javax.swing.JComboBox<String> CBCari;
    private javax.swing.JComboBox<String> CBDokter;
    private javax.swing.JComboBox<String> CBRuangan;
    private javax.swing.JList<String> ListDiagnosa;
    private javax.swing.JTextField TFCari;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFTglLahir;
    private javax.swing.JTextField TFTglMasuk;
    private javax.swing.JTextField TFUsia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel dataPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lk;
    private javax.swing.JRadioButton pr;
    private javax.swing.JPanel tambahPasien;
    // End of variables declaration//GEN-END:variables
}
