
package Postest5;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khosyi
 */
public class TablePengguna extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form TablePengguna
     */
    public TablePengguna() {
        initComponents();
    }
    
    public void InitTable(){
        model = new DefaultTableModel();
        model.addColumn("NAMA");
        model.addColumn("NO. TELEPON");
        model.addColumn("KOTA ASAL");
        Tableisi.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFTelepon = new javax.swing.JTextField();
        CBKota = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BUpdate = new javax.swing.JButton();
        BHapus = new javax.swing.JButton();
        BBersih = new javax.swing.JButton();
        BUlangi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tableisi = new javax.swing.JTable();
        BKeluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TABEL PENGGUNA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(265, 265, 265))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. Telepon");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kota Asal");

        TFNama.setEnabled(false);

        TFTelepon.setEnabled(false);
        TFTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTeleponKeyPressed(evt);
            }
        });

        CBKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samarinda", "Balikpapan", "Paser", "Penajam Paser Utara (PPU)", "Kutai Kartanegara", "Kutai Barat", "Kutai Timur", "Bontang", "Berau" }));
        CBKota.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(*Gunakan Angka)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                            .addComponent(TFNama)
                            .addComponent(CBKota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        BTambah.setText("Tambah / Edit Data");
        BTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTambahMouseExited(evt);
            }
        });
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        jPanel4.add(BTambah);

        BSimpan.setText("Simpan");
        BSimpan.setEnabled(false);
        BSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BSimpanMouseExited(evt);
            }
        });
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(BSimpan);

        BUpdate.setText("Update");
        BUpdate.setEnabled(false);
        BUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BUpdateMouseExited(evt);
            }
        });
        BUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(BUpdate);

        BHapus.setText("Hapus");
        BHapus.setEnabled(false);
        BHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BHapusMouseExited(evt);
            }
        });
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        jPanel4.add(BHapus);

        BBersih.setText("Bersihkan Data");
        BBersih.setEnabled(false);
        BBersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BBersihMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BBersihMouseExited(evt);
            }
        });
        BBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBersihActionPerformed(evt);
            }
        });
        jPanel4.add(BBersih);

        BUlangi.setText("Bersihkan Form");
        BUlangi.setEnabled(false);
        BUlangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BUlangiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BUlangiMouseExited(evt);
            }
        });
        BUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUlangiActionPerformed(evt);
            }
        });
        jPanel4.add(BUlangi);

        Tableisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "No. Telepon", "Kota Asal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tableisi);

        BKeluar.setText("Keluar");
        BKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BKeluarMouseExited(evt);
            }
        });
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        // TODO add your handling code here:
        int baris = Tableisi.getSelectedRow();
        model.removeRow(baris);
    }//GEN-LAST:event_BHapusActionPerformed

    private void BUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUlangiActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFTelepon.setText("");
        TFNama.requestFocus();
    }//GEN-LAST:event_BUlangiActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        if(TFNama.getText().length()==0||TFTelepon.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFNama.requestFocus();
            }
        else{
        Object[] data = new Object[3];
        data[0] = TFNama.getText();
        data[1] = TFTelepon.getText();
        data[2] = CBKota.getSelectedItem().toString();
        model.addRow(data);
        }
   
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUpdateActionPerformed
        // TODO add your handling code here:
        int baris = Tableisi.getSelectedRow();
        
        Tableisi.setValueAt(TFNama.getText(), baris, 0);
        Tableisi.setValueAt(TFTelepon.getText(), baris, 1);
        Tableisi.setValueAt(CBKota.getSelectedItem(), baris, 2);
    }//GEN-LAST:event_BUpdateActionPerformed

    private void BBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBersihActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        TFNama.requestFocus();
    }//GEN-LAST:event_BBersihActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        InitTable();
    }//GEN-LAST:event_formComponentShown

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        // TODO add your handling code here:
        TFNama.setEnabled(true);
        TFTelepon.setEnabled(true);
        CBKota.setEnabled(true);
        BSimpan.setEnabled(true);
        BUpdate.setEnabled(true);
        BHapus.setEnabled(true);
        BBersih.setEnabled(true);
        BUlangi.setEnabled(true);
    }//GEN-LAST:event_BTambahActionPerformed

    private void BTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTambahMouseEntered
        // TODO add your handling code here:
        BTambah.setBackground(Color.ORANGE);
        BTambah.setForeground(Color.BLACK);
    }//GEN-LAST:event_BTambahMouseEntered

    private void BTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTambahMouseExited
        // TODO add your handling code here:
        BTambah.setBackground(Color.WHITE);
        BTambah.setForeground(Color.BLACK);
    }//GEN-LAST:event_BTambahMouseExited

    private void BSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSimpanMouseEntered
        // TODO add your handling code here:
        BSimpan.setBackground(Color.ORANGE);
        BSimpan.setForeground(Color.BLACK);
    }//GEN-LAST:event_BSimpanMouseEntered

    private void BSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSimpanMouseExited
        // TODO add your handling code here:
        BSimpan.setBackground(Color.WHITE);
        BSimpan.setForeground(Color.BLACK);
    }//GEN-LAST:event_BSimpanMouseExited

    private void BUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUpdateMouseEntered
        // TODO add your handling code here:
        BUpdate.setBackground(Color.ORANGE);
        BUpdate.setForeground(Color.BLACK);
    }//GEN-LAST:event_BUpdateMouseEntered

    private void BUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUpdateMouseExited
        // TODO add your handling code here:
        BUpdate.setBackground(Color.WHITE);
        BUpdate.setForeground(Color.BLACK);
    }//GEN-LAST:event_BUpdateMouseExited

    private void BHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHapusMouseEntered
        // TODO add your handling code here:
        BHapus.setBackground(Color.ORANGE);
        BHapus.setForeground(Color.BLACK);
    }//GEN-LAST:event_BHapusMouseEntered

    private void BHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHapusMouseExited
        // TODO add your handling code here:
        BHapus.setBackground(Color.WHITE);
        BHapus.setForeground(Color.BLACK);
    }//GEN-LAST:event_BHapusMouseExited

    private void BBersihMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BBersihMouseEntered
        // TODO add your handling code here:
        BBersih.setBackground(Color.ORANGE);
        BBersih.setForeground(Color.BLACK);
    }//GEN-LAST:event_BBersihMouseEntered

    private void BBersihMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BBersihMouseExited
        // TODO add your handling code here:
        BBersih.setBackground(Color.WHITE);
        BBersih.setForeground(Color.BLACK);
    }//GEN-LAST:event_BBersihMouseExited

    private void BUlangiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUlangiMouseEntered
        // TODO add your handling code here:
        BUlangi.setBackground(Color.ORANGE);
        BUlangi.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_BUlangiMouseEntered

    private void BUlangiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUlangiMouseExited
        // TODO add your handling code here:
        BUlangi.setBackground(Color.WHITE);
        BUlangi.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_BUlangiMouseExited

    private void TFTeleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTeleponKeyPressed
        // TODO add your handling code here:
        TFTelepon.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter1 = e.getKeyChar();
            if(!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                e.consume();
            }
            }
        });
    }//GEN-LAST:event_TFTeleponKeyPressed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BKeluarActionPerformed

    private void BKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseEntered
        // TODO add your handling code here:
        BKeluar.setBackground(Color.ORANGE);
        BKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_BKeluarMouseEntered

    private void BKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseExited
        // TODO add your handling code here:
        BKeluar.setBackground(Color.WHITE);
        BKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_BKeluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablePengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablePengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablePengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablePengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablePengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBersih;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JButton BUlangi;
    private javax.swing.JButton BUpdate;
    private javax.swing.JComboBox<String> CBKota;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFTelepon;
    private javax.swing.JTable Tableisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
