
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author T_Khosyi
 */
public class DataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form DataMahasiswa
     */
    public DataMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFNotlp = new javax.swing.JTextField();
        TFNama = new javax.swing.JTextField();
        TFAlamat = new javax.swing.JTextField();
        TFProdi = new javax.swing.JTextField();
        TFNotlp2 = new javax.swing.JTextField();
        TFNpm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BTNSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NPM");

        jLabel3.setText("Nama");

        jLabel4.setText("Prodi");

        jLabel5.setText("Alamat");

        jLabel6.setText("No. Telepon");

        TFNotlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNotlpActionPerformed(evt);
            }
        });
        TFNotlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNotlpKeyPressed(evt);
            }
        });

        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });
        TFNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNamaKeyPressed(evt);
            }
        });

        TFAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAlamatActionPerformed(evt);
            }
        });
        TFAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFAlamatKeyPressed(evt);
            }
        });

        TFProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFProdiActionPerformed(evt);
            }
        });
        TFProdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFProdiKeyPressed(evt);
            }
        });

        TFNotlp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNotlp2ActionPerformed(evt);
            }
        });
        TFNotlp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNotlp2KeyPressed(evt);
            }
        });

        TFNpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNpmActionPerformed(evt);
            }
        });
        TFNpm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNpmKeyPressed(evt);
            }
        });

        jLabel7.setText("--");

        BTNSimpan.setText("Simpan");
        BTNSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFNpm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFNotlp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(BTNSimpan))
                        .addGap(12, 12, 12)
                        .addComponent(TFNotlp2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFNotlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNotlp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(BTNSimpan)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNotlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNotlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNotlpActionPerformed

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFNamaActionPerformed

    private void TFAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAlamatActionPerformed

    private void TFProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFProdiActionPerformed

    private void TFNotlp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNotlp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNotlp2ActionPerformed

    private void TFNpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNpmActionPerformed

    private void BTNSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSimpanActionPerformed
        // TODO add your handling code here:
            if(TFNpm.getText().length()==0||TFNama.getText().length()==0||TFProdi.getText().length()==0||TFAlamat.getText().length()==0||TFNotlp2.getText().length()==0||TFNotlp.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFNpm.requestFocus();
        return;
            }
            else{
        String Nama = TFNama.getText();
        String Nim = TFNpm.getText();
        String Prodi = TFProdi.getText();
        String Alamat = TFAlamat.getText();
        String Tlp = TFNotlp2.getText();
        String kode = TFNotlp.getText();
        JOptionPane.showMessageDialog(null,"Data Diri Anda Telah Tersimpan");
        JOptionPane.showMessageDialog(null,"NIM\t:"+Nim+"\nNama\t:"+Nama+"\nProdi\t:"+Prodi+"\nAlamat\t:"+Alamat+"\nNo. Telpon\t:"+kode+Tlp);
    }//GEN-LAST:event_BTNSimpanActionPerformed
    }
    private void TFNpmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNpmKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            if(TFNpm.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFNpm.requestFocus();
        return;
            }
            BTNSimpan.requestFocus();
            
        }
            
    }//GEN-LAST:event_TFNpmKeyPressed

    private void TFNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNamaKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == evt.VK_ENTER)
        {
            if(TFNama.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFNama.requestFocus();
        return;
            }
            BTNSimpan.requestFocus();
            
        }
    }//GEN-LAST:event_TFNamaKeyPressed

    private void TFProdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFProdiKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == evt.VK_ENTER)
        {
            if(TFProdi.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFProdi.requestFocus();
        return;
            }
            BTNSimpan.requestFocus();
            
        }
    }//GEN-LAST:event_TFProdiKeyPressed

    private void TFAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAlamatKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
            if(TFAlamat.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFAlamat.requestFocus();
        return;
            }
            BTNSimpan.requestFocus();
            
        }
    }//GEN-LAST:event_TFAlamatKeyPressed

    private void TFNotlpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNotlpKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
            if(TFNotlp.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFNotlp.requestFocus();
        return;
            }
            BTNSimpan.requestFocus();
            
        }
    }//GEN-LAST:event_TFNotlpKeyPressed

    private void TFNotlp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNotlp2KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
            if(TFNotlp2.getText().length()==0)
            {
        JOptionPane.showMessageDialog(null, "Masukkan tidak boleh kosong","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        TFNotlp2.requestFocus();
        return;
            }
            BTNSimpan.requestFocus();
            
        }
    }//GEN-LAST:event_TFNotlp2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSimpan;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNotlp;
    private javax.swing.JTextField TFNotlp2;
    private javax.swing.JTextField TFNpm;
    private javax.swing.JTextField TFProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
