/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Postest4;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Khosyi
 */
public class Khotiki extends javax.swing.JFrame {
    java.util.Date tglsekarang = new java.util.Date();
private SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
//diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
private String tanggal = smpdtfmt.format(tglsekarang);
    /**
     * Creates new form Khotiki
     */
    public Khotiki() {
        initComponents();
        tgl.setText(tanggal);
        setJam();
    }
     public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

            @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

waktu.setText(jam+":"+menit+":"+detik+"");
}
    
};
new Timer(1000, taskPerformer).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TFNamaPengirim = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFTeleponPengirim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFBerat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SDiskon = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        RBReguler = new javax.swing.JRadioButton();
        RBExpress = new javax.swing.JRadioButton();
        Persen = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TFNamaPenerima = new javax.swing.JTextField();
        TFTeleponPenerima = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TFAlamat = new javax.swing.JTextField();
        BHitung = new javax.swing.JButton();
        BUlangi = new javax.swing.JButton();
        BKeluar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAOutput = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        TFTotalTarif = new javax.swing.JTextField();
        tgl = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KHOTIKI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Khosyi Titipan Kilat");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Postest4/b.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 204), 3));

        jLabel4.setText("Nama Pengirim ");

        TFNamaPengirim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNamaPengirimCaretUpdate(evt);
            }
        });
        TFNamaPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaPengirimActionPerformed(evt);
            }
        });

        jLabel5.setText("No. Telepon Pengirim ");

        TFTeleponPengirim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTeleponPengirimCaretUpdate(evt);
            }
        });
        TFTeleponPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTeleponPengirimActionPerformed(evt);
            }
        });
        TFTeleponPengirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTeleponPengirimKeyPressed(evt);
            }
        });

        jLabel6.setText("Berat Barang ");

        TFBerat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFBerat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFBeratCaretUpdate(evt);
            }
        });
        TFBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBeratActionPerformed(evt);
            }
        });
        TFBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFBeratKeyPressed(evt);
            }
        });

        jLabel7.setText("KG");

        jLabel8.setText("Atur Diskon ");

        SDiskon.setMajorTickSpacing(10);
        SDiskon.setPaintLabels(true);
        SDiskon.setPaintTicks(true);
        SDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SDiskonStateChanged(evt);
            }
        });

        jLabel9.setText("Jenis Jasa ");

        buttonGroup1.add(RBReguler);
        RBReguler.setText("Reguler");

        buttonGroup1.add(RBExpress);
        RBExpress.setText("Exspress");
        RBExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBExpressActionPerformed(evt);
            }
        });

        Persen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Persen.setText("50%");

        jLabel12.setText("Nama Penerima ");

        jLabel13.setText("No. Telepon Penerima ");

        TFNamaPenerima.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNamaPenerimaCaretUpdate(evt);
            }
        });
        TFNamaPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaPenerimaActionPerformed(evt);
            }
        });

        TFTeleponPenerima.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTeleponPenerimaCaretUpdate(evt);
            }
        });
        TFTeleponPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTeleponPenerimaActionPerformed(evt);
            }
        });
        TFTeleponPenerima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTeleponPenerimaKeyPressed(evt);
            }
        });

        jLabel14.setText("Alamat Penerima ");

        TFAlamat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFAlamatCaretUpdate(evt);
            }
        });
        TFAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAlamatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TFNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TFTeleponPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(TFNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFTeleponPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TFBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RBReguler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBExpress))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(TFAlamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Persen)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFTeleponPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFTeleponPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBReguler)
                    .addComponent(RBExpress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Persen)
                        .addGap(11, 11, 11)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BHitung.setText("PROSES");
        BHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BHitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BHitungMouseExited(evt);
            }
        });
        BHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHitungActionPerformed(evt);
            }
        });

        BUlangi.setText("ULANGI");
        BUlangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BUlangiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BUlangiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BUlangiMousePressed(evt);
            }
        });
        BUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUlangiActionPerformed(evt);
            }
        });

        BKeluar.setText("KELUAR");
        BKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BKeluarMouseExited(evt);
            }
        });
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        TAOutput.setEditable(false);
        TAOutput.setColumns(20);
        TAOutput.setRows(5);
        jScrollPane1.setViewportView(TAOutput);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("Total Tarif (RP)");

        TFTotalTarif.setEditable(false);
        TFTotalTarif.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TFTotalTarif.setText("RP. ");

        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setText("Tanggal");

        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("Waktu");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFTotalTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tgl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(waktu)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFTotalTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl)
                    .addComponent(waktu))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BUlangi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKeluar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHitung)
                    .addComponent(BKeluar)
                    .addComponent(BUlangi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBExpressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBExpressActionPerformed

    private void TFTeleponPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTeleponPengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTeleponPengirimActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void TFNamaPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaPenerimaActionPerformed

    private void TFTeleponPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTeleponPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTeleponPenerimaActionPerformed

    private void TFAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAlamatActionPerformed

    private void BUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUlangiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUlangiActionPerformed

    private void BHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHitungActionPerformed
        // TODO add your handling code here:
        float Diskon, Reguler=11500, Total=0, Berat, TotalDiskon;
        String NamaPengirim, TeleponPengirim, NamaPenerima, TeleponPenerima, Alamat, Jasa;
        
        NamaPengirim = TFNamaPengirim.getText();
        TeleponPengirim = TFTeleponPengirim.getText();
        NamaPenerima = TFNamaPenerima.getText();
        TeleponPenerima = TFTeleponPenerima.getText();
        Alamat = TFAlamat.getText();
        
        Berat = Float.parseFloat(TFBerat.getText());
        Diskon = Float.valueOf(SDiskon.getValue());
        
        if(RBReguler.isSelected()){
            Jasa = RBReguler.getText();
            TotalDiskon = Reguler * (Diskon/100) * Berat;
            Total = (Reguler * Berat) - TotalDiskon;
        }
        
        else if(RBExpress.isSelected()){
            Jasa = RBExpress.getText();
            TotalDiskon = (float) (Reguler * 1.5 * (Diskon/100) * Berat);
            Total = (float) ((Reguler * Berat* 1.5) - TotalDiskon);
        }
        else {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Jenis Jasa Pengiriman Terlebih Dahulu","PERINGATAN", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        TFTotalTarif.setText("Rp "+Total);
        TAOutput.setText("Struk Pembayaran\n"+
                        "==================================================\n\n"+
                        " Nama Pengirim\t: "+NamaPengirim+
                        "\n No. Telepon Pengirim\t: "+TeleponPengirim+
                        "\n Nama Penerima\t: "+NamaPenerima+
                        "\n No. Telepon Penerima\t: "+TeleponPenerima+
                        "\n Alamat Penerima\t: "+Alamat+
                        "\n Berat\t\t: "+Berat+" Kg"+
                        "\n Diskon\t\t: "+TotalDiskon+
                        "\n Jenis Jasa\t\t: "+Jasa+
                        "\n Total\t\t: Rp "+Total+
                        "\n=================================================="+
                        "\n\nTerima Kasih Telah Memberikan Kepercayaan Kepada Kami"+
                        "\nBersama Kami Kenyamanan Pelanggan Diutamakan"+
                        "\nCEPAT AMAN NYAMAN"+
                        "\n\n\t\t                   \n\n\t\tTaufikurrahman Khosyi\n\t\t        (1515015120)");
    }//GEN-LAST:event_BHitungActionPerformed

    private void BUlangiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUlangiMousePressed
        // TODO add your handling code here:
        TFNamaPengirim.setText("");
        TFTeleponPengirim.setText("");
        TFNamaPenerima.setText("");
        TFTeleponPenerima.setText("");
        TFAlamat.setText("");
        TFBerat.setText("");
        TAOutput.setText("");
        buttonGroup1.clearSelection();
        TFTotalTarif.setText("");
        SDiskon.setValue(50);
    }//GEN-LAST:event_BUlangiMousePressed

    private void TFTeleponPengirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTeleponPengirimKeyPressed
        // TODO add your handling code here:
        TFTeleponPengirim.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter1 = e.getKeyChar();
            if(!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                e.consume();
            }
            }
        }); 
    }//GEN-LAST:event_TFTeleponPengirimKeyPressed

    private void TFTeleponPenerimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTeleponPenerimaKeyPressed
        // TODO add your handling code here:
        TFTeleponPenerima.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter1 = e.getKeyChar();
            if(!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                e.consume();
            }
            }
        });
    }//GEN-LAST:event_TFTeleponPenerimaKeyPressed

    private void TFBeratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFBeratKeyPressed
        // TODO add your handling code here:
        TFBerat.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char karakter1 = e.getKeyChar();
            if(!((karakter1 >= '0') && (karakter1 <= '9')) || (karakter1 == '\b')){
                e.consume();
            }
            }
        });
    }//GEN-LAST:event_TFBeratKeyPressed

    private void TFTeleponPengirimCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTeleponPengirimCaretUpdate
        // TODO add your handling code here:
        if (TFTeleponPenerima.getText().length()== 0 || TFTeleponPengirim.getText().length()==0 || 
            TFNamaPenerima.getText().length()==0 || TFTeleponPenerima.getText().length()==0 || 
            TFAlamat.getText().length()==0 || TFBerat.getText().equals("0")){
            BHitung.setEnabled(false);
        }
        else if (TFNamaPengirim.getText().length()!=0 && TFTeleponPengirim.getText().length()!=0 && TFNamaPenerima.getText().length()!=0
                && TFTeleponPenerima.getText().length()!=0 && TFAlamat.getText().length()!=0 && TFBerat.getText().length()!=0){
            BHitung.setEnabled(true);
        }
//        if ((TFNamaPengirim.getText().length()== 0 ||
//            TFTeleponPengirim.getText().length()== 0 ||
//            TFNamaPenerima.getText().length()== 0 ||
//            TFTeleponPenerima.getText().length()== 0 ||
//            TFAlamat.getText().length()== 0 ||
//            TFBerat.getText().equals("0"))){
//            BHitung.setEnabled(false);
//        }
//        else {
//            BHitung.setEnabled(true);
//        }
    }//GEN-LAST:event_TFTeleponPengirimCaretUpdate

    private void TFNamaPengirimCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNamaPengirimCaretUpdate
        // TODO add your handling code here:
        if (TFTeleponPenerima.getText().length()== 0 || TFTeleponPengirim.getText().length()==0 || 
            TFNamaPenerima.getText().length()==0 || TFTeleponPenerima.getText().length()==0 || 
            TFAlamat.getText().length()==0 || TFBerat.getText().equals("0")){
            BHitung.setEnabled(false);
        }
        else if (TFNamaPengirim.getText().length()!=0 && TFTeleponPengirim.getText().length()!=0 && TFNamaPenerima.getText().length()!=0
                && TFTeleponPenerima.getText().length()!=0 && TFAlamat.getText().length()!=0 && TFBerat.getText().length()!=0){
            BHitung.setEnabled(true);
        }
//        if ((TFNamaPengirim.getText().length()== 0 ||
//            TFTeleponPengirim.getText().length()== 0 ||
//            TFNamaPenerima.getText().length()== 0 ||
//            TFTeleponPenerima.getText().length()== 0 ||
//            TFAlamat.getText().length()== 0 ||
//            TFBerat.getText().equals("0"))){
//            BHitung.setEnabled(false);
//        }
//        else {
//            BHitung.setEnabled(true);
//        }
    }//GEN-LAST:event_TFNamaPengirimCaretUpdate

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BKeluarActionPerformed

    private void SDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SDiskonStateChanged
        // TODO add your handling code here:
        Persen.setText(String.valueOf(SDiskon.getValue()) + "%");
    }//GEN-LAST:event_SDiskonStateChanged

    private void TFBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBeratActionPerformed

    private void TFNamaPenerimaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNamaPenerimaCaretUpdate
        // TODO add your handling code here:
        if (TFTeleponPenerima.getText().length()== 0 || TFTeleponPengirim.getText().length()==0 || 
            TFNamaPenerima.getText().length()==0 || TFTeleponPenerima.getText().length()==0 || 
            TFAlamat.getText().length()==0 || TFBerat.getText().equals("0")){
            BHitung.setEnabled(false);
        }
        else if (TFNamaPengirim.getText().length()!=0 && TFTeleponPengirim.getText().length()!=0 && TFNamaPenerima.getText().length()!=0
                && TFTeleponPenerima.getText().length()!=0 && TFAlamat.getText().length()!=0 && TFBerat.getText().length()!=0){
            BHitung.setEnabled(true);
        }
//        if ((TFNamaPengirim.getText().length()== 0 ||
//            TFTeleponPengirim.getText().length()== 0 ||
//            TFNamaPenerima.getText().length()== 0 ||
//            TFTeleponPenerima.getText().length()== 0 ||
//            TFAlamat.getText().length()== 0 ||
//            TFBerat.getText().equals("0"))){
//            BHitung.setEnabled(false);
//        }
//        else {
//            BHitung.setEnabled(true);
//        }
    }//GEN-LAST:event_TFNamaPenerimaCaretUpdate

    private void TFTeleponPenerimaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTeleponPenerimaCaretUpdate
        // TODO add your handling code here:
        if (TFTeleponPenerima.getText().length()== 0 || TFTeleponPengirim.getText().length()==0 || 
            TFNamaPenerima.getText().length()==0 || TFTeleponPenerima.getText().length()==0 || 
            TFAlamat.getText().length()==0 || TFBerat.getText().equals("0")){
            BHitung.setEnabled(false);
        }
        else if (TFNamaPengirim.getText().length()!=0 && TFTeleponPengirim.getText().length()!=0 && TFNamaPenerima.getText().length()!=0
                && TFTeleponPenerima.getText().length()!=0 && TFAlamat.getText().length()!=0 && TFBerat.getText().length()!=0){
            BHitung.setEnabled(true);
        }
//        if ((TFNamaPengirim.getText().length()== 0 ||
//            TFTeleponPengirim.getText().length()== 0 ||
//            TFNamaPenerima.getText().length()== 0 ||
//            TFTeleponPenerima.getText().length()== 0 ||
//            TFAlamat.getText().length()== 0 ||
//            TFBerat.getText().equals("0"))){
//            BHitung.setEnabled(false);
//        }
//        else {
//            BHitung.setEnabled(true);
//        }
    }//GEN-LAST:event_TFTeleponPenerimaCaretUpdate

    private void TFAlamatCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFAlamatCaretUpdate
        // TODO add your handling code here:
        if (TFTeleponPenerima.getText().length()== 0 || TFTeleponPengirim.getText().length()==0 || 
            TFNamaPenerima.getText().length()==0 || TFTeleponPenerima.getText().length()==0 || 
            TFAlamat.getText().length()==0 || TFBerat.getText().equals("0")){
            BHitung.setEnabled(false);
        }
        else if (TFNamaPengirim.getText().length()!=0 && TFTeleponPengirim.getText().length()!=0 && TFNamaPenerima.getText().length()!=0
                && TFTeleponPenerima.getText().length()!=0 && TFAlamat.getText().length()!=0 && TFBerat.getText().length()!=0){
            BHitung.setEnabled(true);
        }
//        if ((TFNamaPengirim.getText().length()== 0 ||
//            TFTeleponPengirim.getText().length()== 0 ||
//            TFNamaPenerima.getText().length()== 0 ||
//            TFTeleponPenerima.getText().length()== 0 ||
//            TFAlamat.getText().length()== 0 ||
//            TFBerat.getText().equals("0"))){
//            BHitung.setEnabled(false);
//        }
//        else {
//            BHitung.setEnabled(true);
//        }
    }//GEN-LAST:event_TFAlamatCaretUpdate

    private void TFBeratCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFBeratCaretUpdate
        // TODO add your handling code here:
        if (TFTeleponPenerima.getText().length()== 0 || TFTeleponPengirim.getText().length()==0 || 
            TFNamaPenerima.getText().length()==0 || TFTeleponPenerima.getText().length()==0 || 
            TFAlamat.getText().length()==0 || TFBerat.getText().equals("0")){
            BHitung.setEnabled(false);
        }
        else if (TFNamaPengirim.getText().length()!=0 && TFTeleponPengirim.getText().length()!=0 && TFNamaPenerima.getText().length()!=0
                && TFTeleponPenerima.getText().length()!=0 && TFAlamat.getText().length()!=0 && TFBerat.getText().length()!=0){
            BHitung.setEnabled(true);
        }
//        if ((TFNamaPengirim.getText().length()== 0 ||
//            TFTeleponPengirim.getText().length()== 0 ||
//            TFNamaPenerima.getText().length()== 0 ||
//            TFTeleponPenerima.getText().length()== 0 ||
//            TFAlamat.getText().length()== 0 ||
//            TFBerat.getText().equals("0"))){
//            BHitung.setEnabled(false);
//        }
//        else {
//            BHitung.setEnabled(true);
//        }
    }//GEN-LAST:event_TFBeratCaretUpdate

    private void TFNamaPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaPengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaPengirimActionPerformed

    private void BHitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHitungMouseEntered
        // TODO add your handling code here:
        BHitung.setBackground(Color.GREEN);
        BHitung.setForeground(Color.BLACK);
    }//GEN-LAST:event_BHitungMouseEntered

    private void BHitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BHitungMouseExited
        // TODO add your handling code here:
        BHitung.setBackground(Color.WHITE);
        BHitung.setForeground(Color.BLACK);
    }//GEN-LAST:event_BHitungMouseExited

    private void BUlangiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUlangiMouseEntered
        // TODO add your handling code here:
        BUlangi.setBackground(Color.GREEN);
        BUlangi.setForeground(Color.BLACK);
    }//GEN-LAST:event_BUlangiMouseEntered

    private void BUlangiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUlangiMouseExited
        // TODO add your handling code here:
        BUlangi.setBackground(Color.WHITE);
        BUlangi.setForeground(Color.BLACK);
    }//GEN-LAST:event_BUlangiMouseExited

    private void BKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseEntered
        // TODO add your handling code here:
        BKeluar.setBackground(Color.RED);
        BKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_BKeluarMouseEntered

    private void BKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKeluarMouseExited
        // TODO add your handling code here:
        BKeluar.setBackground(Color.WHITE);
        BKeluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_BKeluarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFNamaPengirim.setText("");
        TFTeleponPengirim.setText("");
        TFNamaPenerima.setText("");
        TFTeleponPenerima.setText("");
        TFBerat.setText("");
        TFTotalTarif.setText("");
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Khotiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Khotiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Khotiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Khotiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Khotiki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHitung;
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BUlangi;
    private javax.swing.JLabel Persen;
    private javax.swing.JRadioButton RBExpress;
    private javax.swing.JRadioButton RBReguler;
    private javax.swing.JSlider SDiskon;
    private javax.swing.JTextArea TAOutput;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFBerat;
    private javax.swing.JTextField TFNamaPenerima;
    private javax.swing.JTextField TFNamaPengirim;
    private javax.swing.JTextField TFTeleponPenerima;
    private javax.swing.JTextField TFTeleponPengirim;
    private javax.swing.JTextField TFTotalTarif;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
